services:
  streamlit:
    build: .
    container_name: wingspan-streamlit

    ports:
      - "${STREAMLIT_PORT}:8501"

    env_file:
      - .env

    volumes:
      - ./data:/app/data
      
    restart: unless-stopped