name: wingspan-portal

services:
  django:
    build: .

    depends_on:
      - postgres

    volumes:
      - static_data:/workspace/app/staticfiles

    working_dir: /workspace/app

    expose:
      - "8000"

    restart: unless-stopped

  postgres:
    image: postgres:17

    volumes:
      - postgres_data:/var/lib/postgresql/data/

    restart: unless-stopped

  nginx:
    image: nginx:1.27-alpine

    depends_on:
      - django

    ports:
      - "80:80"

    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - static_data:/usr/share/nginx/html/static:ro

    restart: unless-stopped

volumes:
  postgres_data:
  static_data: