name: wingspan-portal
services:
  django:
    build: .
    container_name: wingspan-django

    env_file:
      - .env

    volumes:
      - .:/workspace

    working_dir: /workspace/app

    ports:
      - "8000:8000"

    command: sleep infinity

    restart: unless-stopped