from django.urls import path

from . import views

app_name = "portal"

urlpatterns = [
    path(
        "", 
        views.home, 
        name="home",
    ),
    path(
        "games/competitive-history/", 
        views.competitive_history, 
        name="competitive_history",
    ),
    path(
        "games/add/", 
        views.GameCreateView.as_view(), 
        name="game-create",
    ),
    path(
        "players/overview/", 
        views.player_overview, 
        name="player-overview",
    ),
    path(
        "players/score-trends/", 
        views.player_score_trends, 
        name="player-score-trends",
    ),
    path(
        "account/", 
        views.account, 
        name="account",
    ),
    path(
        "register/", 
         views.register, 
         name="register",
    ),
    path(
        "games/<int:pk>/", 
        views.game_detail, 
        name="game-detail",
    ),
    path(
        "games/<int:pk>/edit/", 
        views.game_edit, 
        name="game-edit",
    ),
    path(
        "game-results/<int:result_id>/confirm/",
        views.confirm_game_result_view,
        name="game-result-confirm",
    ),
    path(
        "friends/",
        views.friends,
        name="friends",
    ),
    path(
        "friends/send/",
        views.send_friend_request_view,
        name="send-friend-request",
    ),
    path(
        "friends/<int:friend_request_id>/accept/",
        views.accept_friend_request_view,
        name="accept-friend-request",
    ),
    path(
        "friends/<int:player_id>/remove/",
        views.remove_friend_view,
        name="remove-friend",
    ),
    path(
        "friends/<int:friend_request_id>/cancel/",
        views.cancel_friend_request_view,
        name="cancel-friend-request",
    ),
    path(
        "friends/<int:friend_request_id>/decline/",
        views.decline_friend_request_view,
        name="decline-friend-request",
    ),
    path(
        "feathered-foe/",
        views.feathered_foe,
        name="feathered-foe",
    ),
]