# Generated by Django 5.2.16 on 2026-07-23 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='human_player_mode',
            field=models.CharField(choices=[('single_human', 'Solo Game'), ('multi_human', 'Competitive Game')], default='multi_human', max_length=20),
            preserve_default=False,
        ),
    ]
