# Generated by Django 5.2.15 on 2026-07-03 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_played', models.DateField()),
            ],
            options={
                'ordering': ['-date_played', '-id'],
            },
        ),
        migrations.CreateModel(
            name='GameResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turn_order', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('score', models.PositiveSmallIntegerField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='portal.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='game_results', to='portal.player')),
            ],
            options={
                'ordering': ['game', '-score', 'player'],
                'constraints': [models.UniqueConstraint(fields=('game', 'player'), name='unique_player_per_game'), models.UniqueConstraint(fields=('game', 'turn_order'), name='unique_turn_order_per_game')],
            },
        ),
    ]
