# Generated by Django 5.2.17 on 2026-08-31 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_player_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameresult',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
