# Generated by Django 5.2.17 on 2026-09-06 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_confirm_existing_game_results'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='handle',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
