# Generated by Django 5.2.17 on 2026-09-06 22:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_player_handle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='handle',
            field=models.CharField(max_length=32, unique=True, validators=[django.core.validators.RegexValidator(message='Handle must be 3–32 characters, start with a lowercase letter, and contain only lowercase letters, numbers, and underscores.', regex='^[a-z][a-z0-9_]{2,31}$')]),
        ),
    ]
