# Generated by Django 5.2.17 on 2026-09-07 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_alter_player_handle'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Request'), ('accepted', 'Accepted Request'), ('declined', 'Declined Request'), ('cancelled', 'Cancelled Request')], default='pending', max_length=20)),
                ('requestee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_friend_requests', to='portal.player')),
                ('requestor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_friend_requests', to='portal.player')),
            ],
            options={
                'ordering': ['-requested_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('resolved_at__isnull', True), ('status', 'pending')), models.Q(('resolved_at__isnull', False), ('status__in', ['accepted', 'declined', 'cancelled'])), _connector='OR'), name='friend_request_status_resolution_valid'), models.CheckConstraint(condition=models.Q(('requestor', models.F('requestee')), _negated=True), name='friend_request_no_self_request')],
            },
        ),
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('established_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('ended_by_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='friendships_ended', to='portal.player')),
                ('player_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendships_as_player_a', to='portal.player')),
                ('player_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendships_as_player_b', to='portal.player')),
            ],
            options={
                'ordering': ['-established_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('player_a__lt', models.F('player_b'))), name='friendship_canonical_player_order'), models.UniqueConstraint(condition=models.Q(('ended_at__isnull', True)), fields=('player_a', 'player_b'), name='friendship_one_active_per_pair')],
            },
        ),
    ]
